parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: viktis
    database_user: root
    database_password:
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: ru
    secret: 51c3f192d5496a0de72a8b97841498f204314cc8
    database_path: null
    catalog_img:     %kernel.root_dir%/../web/bundles/spbshop/img/catalog/
